// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoteKeeper.Infraestrutura.Orm.Compartilhado;

#nullable disable

namespace NoteKeeper.Infraestrutura.Orm.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoteKeeper.Dominio.ModuloCategoria.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ExcluidoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("NoteKeeper.Dominio.ModuloNota.Nota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("CriadaEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("Excluido")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ExcluidoEmUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Notas");
                });

            modelBuilder.Entity("NoteKeeper.Dominio.ModuloNota.Nota", b =>
                {
                    b.HasOne("NoteKeeper.Dominio.ModuloCategoria.Categoria", "Categoria")
                        .WithMany("Notas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("NoteKeeper.Dominio.ModuloCategoria.Categoria", b =>
                {
                    b.Navigation("Notas");
                });
#pragma warning restore 612, 618
        }
    }
}
